FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

RUN rm -rf /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-get update \
    && apt-get install -y libgl1-mesa-glx build-essential wget git curl libsm6 libxrender1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install anaconda

RUN curl https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh --output conda_installer.sh
RUN /bin/bash conda_installer.sh -b -p /opt/conda \
    && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
    && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc \
    && echo "conda activate base" >> ~/.bashrc \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
    && /opt/conda/bin/conda clean -afy
RUN rm conda_installer.sh

ENV PATH=/opt/conda/bin:$PATH
ENV CUDA_HOME=/usr/local/cuda

# install requirements
# COPY .condarc /root/.condarc
RUN conda install -y numba
# -c nvidia
RUN conda install -y pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 pytorch-cuda=12.4 -c pytorch

RUN pip config set global.index-url https://mirrors.bfsu.edu.cn/pypi/web/simple
RUN pip install --no-cache-dir copious==0.1.23
RUN pip install --no-cache-dir open3d==0.18.0
RUN pip install --no-cache-dir pypcd-imp==0.1.5
RUN pip install --no-cache-dir virtual-camera>=0.0.4.3
RUN pip install --no-cache-dir nuscenes-devkit
RUN pip install --no-cache-dir pytest
RUN pip install --no-cache-dir pytest-cov
RUN pip install --no-cache-dir loguru
RUN pip install --no-cache-dir tqdm
RUN pip install --no-cache-dir opencv-python-headless
RUN pip install --no-cache-dir easydict==1.13
RUN pip install --no-cache-dir scipy==1.14.1
RUN pip install --no-cache-dir mmengine==0.10.5
RUN pip install --no-cache-dir mmdet==3.2.0
RUN pip install --no-cache-dir mmdet3d==1.4.0
RUN pip install --no-cache-dir pypcd-imp==0.1.5
RUN pip install --no-cache-dir transformers==4.45.2

RUN pip install --no-cache-dir openmim
RUN mim install mmcv


# install libgllib2.0
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
   && apt-get install -y libglib2.0-0 libxext6  \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/*

# install pytorch3d
RUN pip install --no-cache-dir --extra-index-url https://miropsota.github.io/torch_packages_builder pytorch3d==0.7.8+pt2.4.1cu124

WORKDIR /workspace

CMD [ "/bin/bash"  ]

