###########################################################
# Fully generated by AI, not verified manually. Paused.
###########################################################
import argparse
import pickle
from pathlib import Path

from loguru import logger
from copious.io.fs import parent_ensured_path

def parse_args():
    parser = argparse.ArgumentParser(description='Separate specified items from input pkl file.')
    parser.add_argument('--input-pkl-path', type=Path, required=True, help='Input file path')
    parser.add_argument('--output-pkl-path', type=Path, required=True, help='Output file path')
    parser.add_argument("--mv4d-data-save-root", type=Path, required=True,
                        help='Root directory to save the separated items.')
    parser.add_argument("--items-to-separate", nargs="+", required=True,
                        help='Items to separate (e.g., 3d_polylines 3d_boxes).')
    return parser.parse_args()

def main(args):
    # Step 1: Load the input pickle file
    logger.info(f"Loading input data from {args.input_pkl_path}")
    with args.input_pkl_path.open('rb') as f:
        data = pickle.load(f)
    logger.info("Input data loaded successfully.")

    # Step 2: Separate the specified items for each scene and frame
    total_separated = 0
    for scene_id, scene_data in data.items():
        frame_info = scene_data.get('frame_info', {})
        for frame_id, frame_data in frame_info.items():
            for item in args.items_to_separate:
                if item in frame_data:
                    item_data = frame_data[item]
                    # Construct the save path
                    save_path = parent_ensured_path(args.mv4d_data_save_root / scene_id / "frame_info_pkl" / item / f"{frame_id}.pkl")
                    # Save the item data to the constructed path
                    with save_path.open('wb') as f_out:
                        pickle.dump(item_data, f_out)
                    # Update the frame_data to reference the saved file path
                    frame_data[item] = str(save_path)
                    total_separated += 1
    logger.info(f"Separated {total_separated} items in total.")

    # Step 3: Save the modified data to the output pickle file
    logger.info(f"Saving modified data to {args.output_pkl_path}")
    with args.output_pkl_path.open('wb') as f_out:
        pickle.dump(data, f_out)
    logger.success("Processing completed successfully.")

if __name__ == '__main__':
    main(parse_args())
